
language: php

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  include:
      - php: 8.1
      - php: 8.2
  fast_finish: true

install:
  - composer install

script:
  - find -name '*.php' -not -path './vendor/*' -name '*.php' | xargs -n1 php -l
